import { supabase } from '@/lib/supabase';

// ─── Types ───────────────────────────────────────────────────────────────────
export type ReportingDivision = 'Division_I' | 'Division_II';

export interface AOC4XBRLData {
  division: ReportingDivision;
  taxonomy: string;                     // 'in-bse/in-mca/2019-04-01' or 'in-ind-as/2019-04-01'
  namespace_uri: string;
  taxonomy_label: string;
  fiscal_year: string;                  // '2025-26'
  period_start: string;                 // 'YYYY-MM-DD'
  period_end: string;
  previous_period_start: string;
  previous_period_end: string;
  entity: {
    user_id: string;
    cin?: string;
    date_of_incorporation?: string;
    reporting_currency?: string;
    msme_classification?: string;
    is_listed?: boolean;
    reporting_division?: ReportingDivision;
  };
  fact_count: number;
  facts: AOC4Fact[];
}

export interface AOC4Fact {
  concept: string;                      // 'in-bse:TradeReceivablesCurrent'
  line_code: string;                    // 'BS.CA.3'
  label: string;
  statement_type: 'BS' | 'PL';
  period_type: 'instant' | 'duration';
  current_value: number;
  previous_value: number;
  decimals: number;
  unit: string;                         // 'INR'
}

// ─── Fetch helper ────────────────────────────────────────────────────────────
export const fetchAOC4XBRLData = async (
  userId: string,
  fiscalYear: string,
  division: ReportingDivision = 'Division_I'
): Promise<AOC4XBRLData | null> => {
  const { data, error } = await supabase.rpc('get_aoc4_xbrl_data', {
    p_user_id: userId,
    p_fiscal_year: fiscalYear,
    p_division: division,
  });
  if (error) {
    console.error('[xbrlGenerator] AOC-4 data fetch error:', error);
    return null;
  }
  return data as AOC4XBRLData;
};

// ─── XML escaping ────────────────────────────────────────────────────────────
const esc = (s: string): string =>
  String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');

// ─── Context generator ───────────────────────────────────────────────────────
// XBRL needs at least: entity scheme + identifier, period (instant or duration).
// We emit one context per (period_type, period) tuple to keep the file compact.
const buildContexts = (data: AOC4XBRLData): string => {
  const entityScheme = 'http://www.mca.gov.in/CIN';
  const entityIdent  = data.entity.cin ?? data.entity.user_id;
  const ctxs: Record<string, string> = {};

  // Current period instant (BS)
  ctxs['I-Current'] = `
  <context id="I-Current">
    <entity><identifier scheme="${esc(entityScheme)}">${esc(entityIdent)}</identifier></entity>
    <period><instant>${esc(data.period_end)}</instant></period>
  </context>`;

  // Previous period instant
  ctxs['I-Previous'] = `
  <context id="I-Previous">
    <entity><identifier scheme="${esc(entityScheme)}">${esc(entityIdent)}</identifier></entity>
    <period><instant>${esc(data.previous_period_end)}</instant></period>
  </context>`;

  // Current period duration (P&L)
  ctxs['D-Current'] = `
  <context id="D-Current">
    <entity><identifier scheme="${esc(entityScheme)}">${esc(entityIdent)}</identifier></entity>
    <period>
      <startDate>${esc(data.period_start)}</startDate>
      <endDate>${esc(data.period_end)}</endDate>
    </period>
  </context>`;

  // Previous period duration
  ctxs['D-Previous'] = `
  <context id="D-Previous">
    <entity><identifier scheme="${esc(entityScheme)}">${esc(entityIdent)}</identifier></entity>
    <period>
      <startDate>${esc(data.previous_period_start)}</startDate>
      <endDate>${esc(data.previous_period_end)}</endDate>
    </period>
  </context>`;

  return Object.values(ctxs).join('');
};

const buildUnits = (): string => `
  <unit id="INR">
    <measure>iso4217:INR</measure>
  </unit>
  <unit id="Pure">
    <measure>xbrli:pure</measure>
  </unit>`;

const factTag = (fact: AOC4Fact, ctxRef: string, value: number): string => {
  // Concept like 'in-bse:TradeReceivablesCurrent' — keep the prefix as-is.
  return `  <${fact.concept} contextRef="${ctxRef}" unitRef="INR" decimals="${fact.decimals}">${value}</${fact.concept}>`;
};

// ─── Build the full XBRL XML ────────────────────────────────────────────────
export const buildAOC4XBRLXML = (data: AOC4XBRLData): string => {
  const lines: string[] = [];
  const isIndAS = data.division === 'Division_II';
  const prefix = isIndAS ? 'in-ind-as' : 'in-bse';
  const schemaHref = isIndAS
    ? 'https://www.mca.gov.in/xbrl/in-ind-as/2019-04-01/in-ind-as-fin-2019-04-01.xsd'
    : 'https://www.bseindia.com/xbrl/2019-04-01/in-bse-fin-2019-04-01.xsd';

  lines.push('<?xml version="1.0" encoding="UTF-8"?>');
  lines.push('<!-- Generated by Aczen Bilz — MCA AOC-4 XBRL emission -->');
  lines.push(`<!-- Division: ${data.division} | Taxonomy: ${data.taxonomy_label} (${data.taxonomy}) -->`);
  lines.push(`<!-- Fiscal Year: ${data.fiscal_year} | Generated: ${new Date().toISOString()} -->`);
  lines.push('<xbrl');
  lines.push('  xmlns="http://www.xbrl.org/2003/instance"');
  lines.push('  xmlns:xbrli="http://www.xbrl.org/2003/instance"');
  lines.push('  xmlns:link="http://www.xbrl.org/2003/linkbase"');
  lines.push('  xmlns:xlink="http://www.w3.org/1999/xlink"');
  lines.push('  xmlns:iso4217="http://www.xbrl.org/2003/iso4217"');
  if (isIndAS) {
    lines.push(`  xmlns:${prefix}="${esc(data.namespace_uri)}">`);
  } else {
    lines.push('  xmlns:in-bse="http://www.bseindia.com/xbrl/fin/2019-04-01/in-bse-fin"');
    lines.push('  xmlns:in-mca="http://www.mca.gov.in/xbrl/in-mca/2019-04-01">');
  }
  lines.push('');
  lines.push(`  <link:schemaRef xlink:type="simple" xlink:href="${schemaHref}"/>`);
  lines.push('');
  lines.push('  <!-- Contexts -->');
  lines.push(buildContexts(data));
  lines.push('');
  lines.push('  <!-- Units -->');
  lines.push(buildUnits());
  lines.push('');
  lines.push('  <!-- Facts -->');
  for (const fact of data.facts) {
    const curCtx  = fact.period_type === 'instant' ? 'I-Current'  : 'D-Current';
    const prevCtx = fact.period_type === 'instant' ? 'I-Previous' : 'D-Previous';

    lines.push(factTag(fact, curCtx, fact.current_value));
    if (fact.previous_value !== 0) {
      lines.push(factTag(fact, prevCtx, fact.previous_value));
    }
  }
  lines.push('</xbrl>');

  return lines.join('\n');
};

// ─── Trigger download ────────────────────────────────────────────────────────
export const downloadAOC4XBRL = (data: AOC4XBRLData, companyName?: string): void => {
  const xml = buildAOC4XBRLXML(data);
  const blob = new Blob([xml], { type: 'application/xml' });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href     = url;
  const suffix = data.division === 'Division_II' ? '_IndAS' : '';
  a.download = `AOC4_XBRL${suffix}_${(companyName || 'Company').replace(/\s+/g, '_')}_FY${data.fiscal_year}.xml`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

// One-call helper: fetch + emit + download.
export const generateAndDownloadAOC4XBRL = async (
  userId: string,
  fiscalYear: string,
  companyName?: string,
  division: ReportingDivision = 'Division_I'
): Promise<{ success: boolean; factCount?: number; error?: string; division?: ReportingDivision }> => {
  const data = await fetchAOC4XBRLData(userId, fiscalYear, division);
  if (!data) return { success: false, error: 'Failed to load AOC-4 data' };
  if (data.fact_count === 0) {
    return { success: false, error: 'No tagged facts found — ensure accounts are classified under Schedule III.' };
  }
  downloadAOC4XBRL(data, companyName);
  return { success: true, factCount: data.fact_count, division };
};
